### ISSUE TITLE
Unable to run the html file even under live server

### ISSUE THREAD

**Issue by skaihahaha** [stc/face-tracking-p5js#4]
Here is the error message I got.

p5.dom.js:1055 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at p5.dom.js:1055

**Comment by stc** [comment]
thanks for pointing it out, I've updated to the latest p5js & ml5js libraries. all examples should work as of now.

**Comment by skaihahaha** [comment]
Thanks. Your work is amazing.
